### ISSUE TITLE
[1.17.1] Crash onstartup (mixin problem)

### ISSUE THREAD

**Issue by mcenderdragon** [gigaherz/ToolBelt#109]
Onstartup before anything is visible it crashes.
Log:
```
Exception in thread "main" java.lang.module.ResolutionException: Module toolbelt reads more than one module named org.spongepowered.mixin
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:729)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

Additional Logs: https://www.toptal.com/developers/hastebin/yamozagiku.sql

**Comment by mcenderdragon** [comment]
probaply something else is wrong, as all mods using mixings have that same error.
