### ISSUE TITLE
initialization error 

### ISSUE THREAD

**Issue by SkarletShadows** [gigaherz/ToolBelt#123]
Forge version: 41-0-87
Minecraft: 1.19

    -- Head --
    Thread: Render thread
    Stacktrace:
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
    -- MOD toolbelt --
    Details:
	    Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderGameOverlayEvent$PreLayer
		    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		    at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		    at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		    at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		    at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
		    at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
		    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Mod File: ToolBelt-1.19-1.19.0.jar
	    Failure message: Tool Belt (toolbelt) has failed to load correctly
		    java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderGameOverlayEvent$PreLayer
	    Mod Version: 1.19.0
	    Mod Issue URL: https://github.com/gigaherz/ToolBelt/issues
	    Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.RenderGameOverlayEvent$PreLayer
    Stacktrace:
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	    at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	    at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	    at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	    at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
	    at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
	    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by gigaherz** [comment]
Hi ToolBelt has not yet been updated for the newer forge versions and will not work on forge versions newer than 41.0.63.
I'm waiting for some dependencies to release updates so I can properly test everything.

**Comment by SkarletShadows** [comment]
Okay, thank you for the information! I figured that was the case but wasn't super sure.
