### ISSUE TITLE
[1.21.x][Neoforge] Crash on game launch

### ISSUE THREAD

**Issue by ffuentesm** [gigaherz/ToolBelt#154]
Neoforge 21.1.50
ToolBelt-1.21-2.2.3
Crashlog: https://pastebin.com/3SFf4Sgb

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/toolbelt@2.2.3/dev.gigaherz.toolbelt.client.ClientEvents.handleKeys(ClientEvents.java:88) ~[ToolBelt-1.21-2.2.3.jar%23468!/:2.2.3] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23152!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23152!/:?] {}
	at TRANSFORMER/neoforge@21.1.50/net.neoforged.neoforge.client.ClientHooks.fireClientTickPre(ClientHooks.java:1069) ~[neoforge-21.1.50-universal.jar%23331!/:?] {re:classloading}

**Comment by gigaherz** [comment]
Hi this crash happens when a previous error has occurred.

[10:55:14] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: hotbarslotcycling, class fuzs.hotbarslotcycling.neoforge.impl.client.HotbarSlotCyclingNeoForgeClient
java.lang.NoSuchFieldError: Class fuzs.puzzleslib.api.client.event.v1.InputEvents does not have member field 'fuzs.puzzleslib.api.event.v1.core.EventInvoker BEFORE_MOUSE_SCROLL'

It would be my guess that the version of "hotbar slot cycling" you are using requires a different version of "puzzles lib"
