### ISSUE TITLE
[1.14.4] Massive log spam - "Supplier should not return null value"

### ISSUE THREAD

**Issue by Phorcis** [gigaherz/ToolBelt#44]
Forge 1.14.4 28.0.76
ToolBelt 1.14.4 1.11.0

9 mb of logs for 3 min
```
[03:18:31] [Client thread/WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
	at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:119) [?:?]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:159) [?:?]
	at gigaherz.toolbelt.client.LayerToolBelt.render(LayerToolBelt.java:43) [?:1.11.0]
	at gigaherz.toolbelt.client.LayerToolBelt.func_212842_a_(LayerToolBelt.java:21) [?:1.11.0]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_177093_a(LivingRenderer.java:394) [?:?]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_76986_a(LivingRenderer.java:143) [?:?]
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_76986_a(PlayerRenderer.java:62) [?:?]
	at net.minecraft.client.renderer.entity.PlayerRenderer.func_76986_a(PlayerRenderer.java:33) [?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) [?:?]
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_147046_a(SourceFile:142) [?:?]
	at gigaherz.toolbelt.common.BeltSlotScreen.func_146976_a(BeltSlotScreen.java:100) [?:1.11.0]
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:75) [?:?]
	at net.minecraft.client.gui.DisplayEffectsScreen.render(DisplayEffectsScreen.java:45) [?:?]
	at gigaherz.toolbelt.common.BeltSlotScreen.render(BeltSlotScreen.java:81) [?:1.11.0]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:360) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.76.jar:28.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$343/1299145277.call(Unknown Source) [forge-1.14.4-28.0.76.jar:28.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?]
```

**Comment by gigaherz** [comment]
I'll take a look as soon as I can.

**Comment by gigaherz** [comment]
Sorry that it took me this long. I found the cause and fixed it.
