### ISSUE TITLE
Interaction Issues

### ISSUE THREAD

**Issue by LtMuffler** [gigaherz/ToolBelt#55]
Hello, I just installed your 1.12.2-1.9.12 version of ToolBelt onto our server running the next to latest version of the Roguelike Adventures and Dungeons modpack with the latest version of Trinkets and Baubles added in. 

Your mod itself functioned fine, however there was an issue with interacting with objects and npcs while something was in the selected quickslot. npcs would fail to interact, and objects like doors would interact but fail to change their state (so a door would "open" but I wouldn't be able to walk through". In addition, I attempted to make dragonsteel ingots in the Ice and Fire mod's dragonforge, but it failed to interact with the chained dragon's fire.

Uninstalling the mod resolved all issues. I'm not sure which of the logs covers the portion of server time which saw the server running the mod, but if this is a new issue and you have no precedence then I can look at them and see if I can't figure out which log is the correct one.

**Comment by gigaherz** [comment]
Logs would be appreciated. It sounds like something may be causing the interaction attempts to soft-crash. I have never heard of anything like that, so it may be an unexpected interaction between mods.

**Comment by LtMuffler** [comment]
[2019-11-02-5.log](https://github.com/gigaherz/ToolBelt/files/3801602/2019-11-02-5.log)

**Comment by LtMuffler** [comment]
In that log, I was at one base, created the toolbelt, gave myself a bunch of pouches, added them to the toolbelt and put my tools in there, and then flew on my dragon "falhofgr" back to my base ~8km east. Made a few pitstops which included a wizards tower, some dragon nests, etc. I noticed the interaction issue with the wizard and some chests but didn't worry about it too much. 

Once I got back to my base, I noticed the issue with the doors, and the last thing I tried to do was make dragonsteel in the forge but it didn't respond to the dragon's breath at all. At that point I logged off, removed the mod, and restarted the server.

**Comment by gigaherz** [comment]
I'm not seeing anything in that log that suggests ToolBelt had anything to do with the problem. 
That looks like a dedicated server log. Do you have a client log?

If the client log doesn't have anything, I have to assume some other mod is causing the problem, but just happens to not trigger when my mod isn't present.

**Comment by LtMuffler** [comment]
[2019-11-02-5.log](https://github.com/gigaherz/ToolBelt/files/3825824/2019-11-02-5.log)
This is the log from my client, i did give you the server log before.

**Comment by gigaherz** [comment]
I see 2 suspicious things in that log. The first one is 
```
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockDoublePlant$EnumPlantType, values=[sunflower, syringa, double_grass, double_fern, double_rose, paeonia]} as it does not exist in BlockStateContainer{block=minecraft:leaves, properties=[check_decay, decayable, variant]}
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at extendedrenderer.particle.entity.ParticleTexLeafColor.<init>(ParticleTexLeafColor.java:60)
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.profileSurroundings(SceneEnhancer.java:1719)
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.tickClientThreaded(SceneEnhancer.java:240)
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at weather2.client.SceneEnhancer.run(SceneEnhancer.java:177)
[18:27:28] [Weather2 Scene Enhancer/INFO]: [weather2.client.SceneEnhancer:run:180]: 	at java.lang.Thread.run(Thread.java:745)
```

which doesn't seem to me like it's specifically going to cause the interaction issue you describe, and wouldn't be fixed by removing toolbelt,

The second, is a series of entity-related crashes, like this:
```
Caused by: java.lang.NullPointerException
    at net.minecraft.client.network.NetHandlerPlayClient.handleEntityProperties(NetHandlerPlayClient.java:2084)
    at net.minecraft.network.play.server.SPacketEntityProperties.processPacket(SourceFile:70)
    at net.minecraft.network.play.server.SPacketEntityProperties.processPacket(SourceFile:15)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more
```

which seems to happen over and over for different entity-related packets. This could explain the client misbehaving. However, that still doesn't seem like it's ToolBelt's fault, since I don't send any entity-related packets, and the stack traces don't have anything that implicates my mod.

Knowing that you are playing the RAD modpack, I can attempt to install an instance and see if I can cause it to happen locally, but I can't promise that I will be able to track down the real cause.

**Comment by LtMuffler** [comment]
If you can't recreate the issue, then that's just how it is, thank you for your hard work already! My internet is decently poor so I sometimes have connection related issues with interaction and randomly DCing to menu, but I haven't had that issue at all since uninstalling ToolBelt, and we've since installed the better portals mod. The other two mods not default to the pack are the Trinkets and Baubles mod and the mod that adds the crazy storms like tornadoes and such. I can't remember if those were already installed on the server before TB or if we installed them after.
